# .github/workflows/cd.yml
name: 'Deploy'     # Name of the action.
on: ['deployment'] # Listen for deployment events.
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'  # Checkout the repository code.
        uses: 'actions/checkout@v1'
      - name: 'Deploy'
        run: echo My secret is ${{ mysecret }}